// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// ProjectTasksColumns holds the columns for the "project_tasks" table.
	ProjectTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_project_tasks", Type: field.TypeUUID},
		{Name: "task_project_tasks", Type: field.TypeUUID},
	}
	// ProjectTasksTable holds the schema information for the "project_tasks" table.
	ProjectTasksTable = &schema.Table{
		Name:       "project_tasks",
		Columns:    ProjectTasksColumns,
		PrimaryKey: []*schema.Column{ProjectTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_tasks_projects_project_tasks",
				Columns:    []*schema.Column{ProjectTasksColumns[2]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_tasks_tasks_project_tasks",
				Columns:    []*schema.Column{ProjectTasksColumns[3]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projecttask_project_project_tasks_task_project_tasks",
				Unique:  true,
				Columns: []*schema.Column{ProjectTasksColumns[2], ProjectTasksColumns[3]},
			},
		},
	}
	// ProjectUsersColumns holds the columns for the "project_users" table.
	ProjectUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "member", "viewer"}, Default: "member"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_memberships", Type: field.TypeUUID},
		{Name: "user_memberships", Type: field.TypeUUID},
	}
	// ProjectUsersTable holds the schema information for the "project_users" table.
	ProjectUsersTable = &schema.Table{
		Name:       "project_users",
		Columns:    ProjectUsersColumns,
		PrimaryKey: []*schema.Column{ProjectUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_users_projects_memberships",
				Columns:    []*schema.Column{ProjectUsersColumns[3]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_users_users_memberships",
				Columns:    []*schema.Column{ProjectUsersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectuser_project_memberships_user_memberships",
				Unique:  true,
				Columns: []*schema.Column{ProjectUsersColumns[3], ProjectUsersColumns[4]},
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"todo", "in_progress", "done"}, Default: "todo"},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"low", "medium", "high"}, Default: "medium"},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserTasksColumns holds the columns for the "user_tasks" table.
	UserTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "task_assignments", Type: field.TypeUUID},
		{Name: "user_assignments", Type: field.TypeUUID},
	}
	// UserTasksTable holds the schema information for the "user_tasks" table.
	UserTasksTable = &schema.Table{
		Name:       "user_tasks",
		Columns:    UserTasksColumns,
		PrimaryKey: []*schema.Column{UserTasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tasks_tasks_assignments",
				Columns:    []*schema.Column{UserTasksColumns[2]},
				RefColumns: []*schema.Column{TasksColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_tasks_users_assignments",
				Columns:    []*schema.Column{UserTasksColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usertask_user_assignments_task_assignments",
				Unique:  true,
				Columns: []*schema.Column{UserTasksColumns[3], UserTasksColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		ProjectTasksTable,
		ProjectUsersTable,
		TasksTable,
		UsersTable,
		UserTasksTable,
	}
)

func init() {
	ProjectTasksTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectTasksTable.ForeignKeys[1].RefTable = TasksTable
	ProjectUsersTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectUsersTable.ForeignKeys[1].RefTable = UsersTable
	UserTasksTable.ForeignKeys[0].RefTable = TasksTable
	UserTasksTable.ForeignKeys[1].RefTable = UsersTable
}
