// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager-dashboard-go/ent/predicate"
	"project-manager-dashboard-go/ent/project"
	"project-manager-dashboard-go/ent/projecttask"
	"project-manager-dashboard-go/ent/task"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectTaskUpdate is the builder for updating ProjectTask entities.
type ProjectTaskUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectTaskMutation
}

// Where appends a list predicates to the ProjectTaskUpdate builder.
func (_u *ProjectTaskUpdate) Where(ps ...predicate.ProjectTask) *ProjectTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectTaskUpdate) SetCreatedAt(v time.Time) *ProjectTaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectTaskUpdate) SetNillableCreatedAt(v *time.Time) *ProjectTaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectTaskUpdate) SetProjectID(id uuid.UUID) *ProjectTaskUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectTaskUpdate) SetProject(v *Project) *ProjectTaskUpdate {
	return _u.SetProjectID(v.ID)
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *ProjectTaskUpdate) SetTaskID(id uuid.UUID) *ProjectTaskUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *ProjectTaskUpdate) SetTask(v *Task) *ProjectTaskUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the ProjectTaskMutation object of the builder.
func (_u *ProjectTaskUpdate) Mutation() *ProjectTaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectTaskUpdate) ClearProject() *ProjectTaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *ProjectTaskUpdate) ClearTask() *ProjectTaskUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTaskUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTask.project"`)
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTask.task"`)
	}
	return nil
}

func (_u *ProjectTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttask.Table, projecttask.Columns, sqlgraph.NewFieldSpec(projecttask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(projecttask.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.ProjectTable,
			Columns: []string{projecttask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.ProjectTable,
			Columns: []string{projecttask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.TaskTable,
			Columns: []string{projecttask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.TaskTable,
			Columns: []string{projecttask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectTaskUpdateOne is the builder for updating a single ProjectTask entity.
type ProjectTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectTaskMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectTaskUpdateOne) SetCreatedAt(v time.Time) *ProjectTaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectTaskUpdateOne) SetNillableCreatedAt(v *time.Time) *ProjectTaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ProjectTaskUpdateOne) SetProjectID(id uuid.UUID) *ProjectTaskUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectTaskUpdateOne) SetProject(v *Project) *ProjectTaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *ProjectTaskUpdateOne) SetTaskID(id uuid.UUID) *ProjectTaskUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *ProjectTaskUpdateOne) SetTask(v *Task) *ProjectTaskUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the ProjectTaskMutation object of the builder.
func (_u *ProjectTaskUpdateOne) Mutation() *ProjectTaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectTaskUpdateOne) ClearProject() *ProjectTaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *ProjectTaskUpdateOne) ClearTask() *ProjectTaskUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the ProjectTaskUpdate builder.
func (_u *ProjectTaskUpdateOne) Where(ps ...predicate.ProjectTask) *ProjectTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectTaskUpdateOne) Select(field string, fields ...string) *ProjectTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectTask entity.
func (_u *ProjectTaskUpdateOne) Save(ctx context.Context) (*ProjectTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectTaskUpdateOne) SaveX(ctx context.Context) *ProjectTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectTaskUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTask.project"`)
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectTask.task"`)
	}
	return nil
}

func (_u *ProjectTaskUpdateOne) sqlSave(ctx context.Context) (_node *ProjectTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projecttask.Table, projecttask.Columns, sqlgraph.NewFieldSpec(projecttask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projecttask.FieldID)
		for _, f := range fields {
			if !projecttask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projecttask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(projecttask.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.ProjectTable,
			Columns: []string{projecttask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.ProjectTable,
			Columns: []string{projecttask.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.TaskTable,
			Columns: []string{projecttask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projecttask.TaskTable,
			Columns: []string{projecttask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projecttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
