// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager-dashboard-go/ent/project"
	"project-manager-dashboard-go/ent/projectuser"
	"project-manager-dashboard-go/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProjectUser is the model entity for the ProjectUser schema.
type ProjectUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Role holds the value of the "role" field.
	Role projectuser.Role `json:"role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectUserQuery when eager-loading is set.
	Edges               ProjectUserEdges `json:"edges"`
	project_memberships *uuid.UUID
	user_memberships    *uuid.UUID
	selectValues        sql.SelectValues
}

// ProjectUserEdges holds the relations/edges for other nodes in the graph.
type ProjectUserEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectUserEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectuser.FieldRole:
			values[i] = new(sql.NullString)
		case projectuser.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case projectuser.FieldID:
			values[i] = new(uuid.UUID)
		case projectuser.ForeignKeys[0]: // project_memberships
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case projectuser.ForeignKeys[1]: // user_memberships
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectUser fields.
func (_m *ProjectUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectuser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectuser.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = projectuser.Role(value.String)
			}
		case projectuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectuser.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_memberships", values[i])
			} else if value.Valid {
				_m.project_memberships = new(uuid.UUID)
				*_m.project_memberships = *value.S.(*uuid.UUID)
			}
		case projectuser.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_memberships", values[i])
			} else if value.Valid {
				_m.user_memberships = new(uuid.UUID)
				*_m.user_memberships = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectUser.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectUser entity.
func (_m *ProjectUser) QueryProject() *ProjectQuery {
	return NewProjectUserClient(_m.config).QueryProject(_m)
}

// QueryUser queries the "user" edge of the ProjectUser entity.
func (_m *ProjectUser) QueryUser() *UserQuery {
	return NewProjectUserClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ProjectUser.
// Note that you need to call ProjectUser.Unwrap() before calling this method if this ProjectUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectUser) Update() *ProjectUserUpdateOne {
	return NewProjectUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectUser) Unwrap() *ProjectUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectUser) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectUsers is a parsable slice of ProjectUser.
type ProjectUsers []*ProjectUser
