// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager-dashboard-go/ent/project"
	"project-manager-dashboard-go/ent/projecttask"
	"project-manager-dashboard-go/ent/task"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ProjectTask is the model entity for the ProjectTask schema.
type ProjectTask struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectTaskQuery when eager-loading is set.
	Edges                 ProjectTaskEdges `json:"edges"`
	project_project_tasks *uuid.UUID
	task_project_tasks    *uuid.UUID
	selectValues          sql.SelectValues
}

// ProjectTaskEdges holds the relations/edges for other nodes in the graph.
type ProjectTaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectTaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectTaskEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projecttask.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case projecttask.FieldID:
			values[i] = new(uuid.UUID)
		case projecttask.ForeignKeys[0]: // project_project_tasks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case projecttask.ForeignKeys[1]: // task_project_tasks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectTask fields.
func (_m *ProjectTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projecttask.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projecttask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projecttask.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_project_tasks", values[i])
			} else if value.Valid {
				_m.project_project_tasks = new(uuid.UUID)
				*_m.project_project_tasks = *value.S.(*uuid.UUID)
			}
		case projecttask.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field task_project_tasks", values[i])
			} else if value.Valid {
				_m.task_project_tasks = new(uuid.UUID)
				*_m.task_project_tasks = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectTask.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectTask entity.
func (_m *ProjectTask) QueryProject() *ProjectQuery {
	return NewProjectTaskClient(_m.config).QueryProject(_m)
}

// QueryTask queries the "task" edge of the ProjectTask entity.
func (_m *ProjectTask) QueryTask() *TaskQuery {
	return NewProjectTaskClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this ProjectTask.
// Note that you need to call ProjectTask.Unwrap() before calling this method if this ProjectTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectTask) Update() *ProjectTaskUpdateOne {
	return NewProjectTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectTask) Unwrap() *ProjectTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectTask) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectTasks is a parsable slice of ProjectTask.
type ProjectTasks []*ProjectTask
