// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project-manager-dashboard-go/ent/project"
	"project-manager-dashboard-go/ent/projecttask"
	"project-manager-dashboard-go/ent/projectuser"
	"project-manager-dashboard-go/ent/schema"
	"project-manager-dashboard-go/ent/task"
	"project-manager-dashboard-go/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[3].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	projecttaskFields := schema.ProjectTask{}.Fields()
	_ = projecttaskFields
	// projecttaskDescCreatedAt is the schema descriptor for created_at field.
	projecttaskDescCreatedAt := projecttaskFields[1].Descriptor()
	// projecttask.DefaultCreatedAt holds the default value on creation for the created_at field.
	projecttask.DefaultCreatedAt = projecttaskDescCreatedAt.Default.(func() time.Time)
	// projecttaskDescID is the schema descriptor for id field.
	projecttaskDescID := projecttaskFields[0].Descriptor()
	// projecttask.DefaultID holds the default value on creation for the id field.
	projecttask.DefaultID = projecttaskDescID.Default.(func() uuid.UUID)
	projectuserFields := schema.ProjectUser{}.Fields()
	_ = projectuserFields
	// projectuserDescCreatedAt is the schema descriptor for created_at field.
	projectuserDescCreatedAt := projectuserFields[2].Descriptor()
	// projectuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectuser.DefaultCreatedAt = projectuserDescCreatedAt.Default.(func() time.Time)
	// projectuserDescID is the schema descriptor for id field.
	projectuserDescID := projectuserFields[0].Descriptor()
	// projectuser.DefaultID holds the default value on creation for the id field.
	projectuser.DefaultID = projectuserDescID.Default.(func() uuid.UUID)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPosition is the schema descriptor for position field.
	taskDescPosition := taskFields[5].Descriptor()
	// task.DefaultPosition holds the default value on creation for the position field.
	task.DefaultPosition = taskDescPosition.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[7].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[8].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
