// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectTask is the predicate function for projecttask builders.
type ProjectTask func(*sql.Selector)

// ProjectUser is the predicate function for projectuser builders.
type ProjectUser func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserTask is the predicate function for usertask builders.
type UserTask func(*sql.Selector)
